"use client";

import { useState } from 'react';
import { useRouter } from 'next/navigation';

export default function ReleaseManager({ campaigns }: { campaigns: Array<{ id: string; name: string }> }) {
  const router = useRouter(); const [message,setMessage]=useState<string|null>(null); const [pending,setPending]=useState(false);
  async function create(formData: FormData){setPending(true);setMessage(null);try{const response=await fetch('/api/data-lab/releases',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({version:String(formData.get('version')),campaignId:String(formData.get('campaignId')),recipe:{goldWeight:Number(formData.get('goldWeight')),silverWeight:Number(formData.get('silverWeight')),includeHumanGold:true,includeReviewedSilver:true}})});const data=await response.json();if(!response.ok)throw new Error(data.error??'创建失败');setMessage('发布草稿已创建');router.refresh();}catch(error){setMessage(error instanceof Error?error.message:String(error));}finally{setPending(false)}}
  return <form action={create} className="grid gap-3 border bg-white p-4 md:grid-cols-4"><label className="text-sm">版本号<input name="version" required placeholder="stem-sft-v1" className="mt-1 w-full border px-3 py-2" /></label><label className="text-sm">标注活动<select name="campaignId" required className="mt-1 w-full border px-3 py-2"><option value="">请选择</option>{campaigns.map((campaign)=><option key={campaign.id} value={campaign.id}>{campaign.name}</option>)}</select></label><label className="text-sm">Gold权重<input name="goldWeight" type="number" step="0.1" defaultValue="1.5" className="mt-1 w-full border px-3 py-2" /></label><label className="text-sm">Silver权重<input name="silverWeight" type="number" step="0.1" defaultValue="1" className="mt-1 w-full border px-3 py-2" /></label><div className="flex items-center gap-3 md:col-span-4"><button disabled={pending} className="bg-gray-950 px-4 py-2 text-sm text-white">创建版本草稿</button>{message&&<span className="text-sm text-gray-600">{message}</span>}</div></form>
}

export function FreezeReleaseButton({ id }: { id: string }) { const router=useRouter();const [pending,setPending]=useState(false);const [error,setError]=useState<string|null>(null);async function freeze(){setPending(true);setError(null);try{const response=await fetch(`/api/data-lab/releases/${id}/freeze`,{method:'POST'});const data=await response.json();if(!response.ok)throw new Error(data.error??'冻结失败');router.refresh();}catch(err){setError(err instanceof Error?err.message:String(err));}finally{setPending(false)}}return <div><button onClick={freeze} disabled={pending} className="border border-gray-900 px-3 py-1 text-xs">{pending?'冻结中…':'冻结发布'}</button>{error&&<div className="mt-1 text-xs text-red-600">{error}</div>}</div>}
